field.value.date_recur:
  type: field.value.daterange
  label: 'Default value'

field.storage_settings.date_recur:
  type: field.storage_settings.daterange
  label: 'Date recur settings'
  mapping:
    occurrence_handler_plugin:
      type: string
      label: 'Occurrence handler plugin'

field.field_settings.date_recur:
  type: mapping
  label: 'Integer'
  mapping:
    precreate:
      type: string
      label: 'Precreate interval'

field.formatter.settings.date_recur_default_formatter:
  type: field.formatter.settings.daterange_default
  label: 'Default date recur formatter.'
  mapping:
    show_next:
      type: integer
    count_per_item:
      type: boolean
    occurrence_format_type:
      type: string
    same_end_date_format_type:
      type: string
    interpreter:
      type: string

date_recur.interpreter.*:
  type: config_entity
  label: 'Date format'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin type'
    settings:
      type: date_recur.interpreter.settings.[%parent.plugin]


date_recur.interpreter.settings.*:
  type: date_recur_interpreter_settings_base

date_recur_interpreter_settings_base:
  type: mapping
  label: 'Base settings for date recur interpreters'
  mapping: []

date_recur.interpreter.settings.rl:
  type: mapping
  mapping:
    show_start_date:
      type: boolean
    show_until:
      type: boolean
    date_format:
      type: string
    show_infinite:
      type: boolean
